### ISSUE TITLE
才调用了两下（成功），GPT账号就被封了怎么办？

### ISSUE THREAD

**Issue by wt616** [aiqinxuancai/ChatGPTSharp#2]
如题，你被封过吗？我之前用KEY在开源网页里很好用，但用了你的SDK后，试了两把，然后就被封了，这是啥原因

**Comment by aiqinxuancai** [comment]
照这么说我应该在调试的时候就被封了...他封号的机制我不清楚，这里只是实现他官方文档的API及Token数量算法，我觉得和用什么库没有关系。
建议看看这个 https://51.ruyo.net/18313.html

**Comment by wt616** [comment]
好的，谢谢，另外我想请教下，API访问时，电脑IP也必须是国外的吗？

**Comment by aiqinxuancai** [comment]
> 好的，谢谢，另外我想请教下，API访问时，电脑IP也必须是国外的吗？

初始化那里可以设置代理
