### ISSUE TITLE
gpt-3.5-turbo-16k model is not working

### ISSUE THREAD

**Issue by paulofloresjunior** [aiqinxuancai/ChatGPTSharp#3]
Hello,

I'm trying to use 16k model but I'm getting the exception System.NotImplementedException: 'Unsupported model'.

Have any ideias? 

Thanks

**Comment by aiqinxuancai** [comment]
Hello, Please use TiktokenSharp 1.0.7.

**Comment by paulofloresjunior** [comment]
Hi, now is working fine! Thanks!
