### ISSUE TITLE
How to set another request parameters?

### ISSUE THREAD

**Issue by lofti198** [aiqinxuancai/ChatGPTSharp#5]
Hi! Great library. How to set another request parameters like max_tokens for instance?

**Comment by aiqinxuancai** [comment]
Usually, max_tokens is automatically adjusted based on the model, but due to the model being updated at any time, there may not be such timely adaptation. You can specify:
```csharp
settings.ModelName = "gpt-4-vision-preview";
// After setting ModelName
settings.MaxContextTokens = your value;
settings.MaxResponseTokens = your value;
settings.MaxPromptTokens = your value;
```

**Comment by lofti198** [comment]
Thank you!!!!
